---
- hosts: localhost
  connection: local
  sudo: yes

  vars_files:
    - variables.yml

  tasks:
    - include: tasks/base/oracle_java8.yml

- hosts: localhost
  connection: local
  
  vars_files:
    - variables.yml
  
  sudo: no
  tasks:
    - include: tasks/dev/intellij_idea.yml
